<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDb93m9r\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDb93m9r/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDb93m9r.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDb93m9r\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerDb93m9r\appTestDebugProjectContainer([
    'container.build_hash' => 'Db93m9r',
    'container.build_id' => '1900f9a2',
    'container.build_time' => 1694958535,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDb93m9r');
