<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHr4kip4\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHr4kip4/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHr4kip4.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHr4kip4\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerHr4kip4\appTestDebugProjectContainer([
    'container.build_hash' => 'Hr4kip4',
    'container.build_id' => 'ad9ce7ca',
    'container.build_time' => 1687451444,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHr4kip4');
