<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVwt1xvu\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVwt1xvu/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVwt1xvu.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVwt1xvu\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerVwt1xvu\appTestDebugProjectContainer([
    'container.build_hash' => 'Vwt1xvu',
    'container.build_id' => '1d839d92',
    'container.build_time' => 1686503731,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVwt1xvu');
