<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSndcmil\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSndcmil/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSndcmil.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSndcmil\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerSndcmil\appDevDebugProjectContainer([
    'container.build_hash' => 'Sndcmil',
    'container.build_id' => 'e37affd6',
    'container.build_time' => 1686503697,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSndcmil');
