<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRrrdnet\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRrrdnet/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRrrdnet.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRrrdnet\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRrrdnet\appDevDebugProjectContainer([
    'container.build_hash' => 'Rrrdnet',
    'container.build_id' => '090e0cb0',
    'container.build_time' => 1687466911,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRrrdnet');
