<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerXxosu2r\appDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerXxosu2r/appDevDebugProjectContainer.php';
}

if (!class_exists(appDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerXxosu2r\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXxosu2r\appDevDebugProjectContainer();
